# Fetched from https://github.com/dwyl/english-words
dictionary.path=words_alpha.txt
number.of.words=3
shortener.rate-limit.enabled=true
shortener.rate-limit.requests-per-minute=30
shortener.rate-limit.max-identities=10000
